package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BookingStatus generated by hbm2java
 */
@Entity
@Table(name = "booking_status", catalog = "bookall")
public class BookingStatus implements java.io.Serializable {

	private Long id;
	private String name;
	private Set<Bookings> bookingses = new HashSet<Bookings>(0);

	public BookingStatus() {
	}

	public BookingStatus(String name) {
		this.name = name;
	}

	public BookingStatus(String name, Set<Bookings> bookingses) {
		this.name = name;
		this.bookingses = bookingses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bookingStatus")
	public Set<Bookings> getBookingses() {
		return this.bookingses;
	}

	public void setBookingses(Set<Bookings> bookingses) {
		this.bookingses = bookingses;
	}

}
