package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BookingMethodes generated by hbm2java
 */
@Entity
@Table(name = "booking_methodes", catalog = "bookall")
public class BookingMethodes implements java.io.Serializable {

	private Long id;
	private String name;
	private Set<Bookings> bookingses = new HashSet<Bookings>(0);
	private Set<Bookings> bookingses_1 = new HashSet<Bookings>(0);

	public BookingMethodes() {
	}

	public BookingMethodes(String name) {
		this.name = name;
	}

	public BookingMethodes(String name, Set<Bookings> bookingses, Set<Bookings> bookingses_1) {
		this.name = name;
		this.bookingses = bookingses;
		this.bookingses_1 = bookingses_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bookingMethodes")
	public Set<Bookings> getBookingses() {
		return this.bookingses;
	}

	public void setBookingses(Set<Bookings> bookingses) {
		this.bookingses = bookingses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bookingMethodes")
	public Set<Bookings> getBookingses_1() {
		return this.bookingses_1;
	}

	public void setBookingses_1(Set<Bookings> bookingses_1) {
		this.bookingses_1 = bookingses_1;
	}

}
