package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * BusinessCategories generated by hbm2java
 */
@Entity
@Table(name = "business_categories", catalog = "bookall")
public class BusinessCategories implements java.io.Serializable {

	private long categoryId;
	private Categories categories;
	private Set<Businesses> businesseses = new HashSet<Businesses>(0);

	public BusinessCategories() {
	}

	public BusinessCategories(Categories categories) {
		this.categories = categories;
	}

	public BusinessCategories(Categories categories, Set<Businesses> businesseses) {
		this.categories = categories;
		this.businesseses = businesseses;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "categories"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "category_id", unique = true, nullable = false)
	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessCategories")
	public Set<Businesses> getBusinesseses() {
		return this.businesseses;
	}

	public void setBusinesseses(Set<Businesses> businesseses) {
		this.businesseses = businesseses;
	}

}
