package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Businesses generated by hbm2java
 */
@Entity
@Table(name = "businesses", catalog = "bookall")
public class Businesses implements java.io.Serializable {

	private Long id;
	private BusinessCategories businessCategories;
	private Cities cities;
	private Countries countries;
	private ServiceProviders serviceProviders;
	private String name;
	private String adress;
	private String email;
	private String phone;
	private String zip;
	private String street;
	private double longitude;
	private double latitude;
	private Date createdAt;
	private Date updatedAt;
	private String description;

	public Businesses() {
	}

	public Businesses(BusinessCategories businessCategories, Cities cities, Countries countries,
			ServiceProviders serviceProviders, String name, String adress, String email, String phone, String zip,
			String street, double longitude, double latitude, Date createdAt, Date updatedAt, String description) {
		this.businessCategories = businessCategories;
		this.cities = cities;
		this.countries = countries;
		this.serviceProviders = serviceProviders;
		this.name = name;
		this.adress = adress;
		this.email = email;
		this.phone = phone;
		this.zip = zip;
		this.street = street;
		this.longitude = longitude;
		this.latitude = latitude;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category", nullable = false)
	public BusinessCategories getBusinessCategories() {
		return this.businessCategories;
	}

	public void setBusinessCategories(BusinessCategories businessCategories) {
		this.businessCategories = businessCategories;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "city_fk", nullable = false)
	public Cities getCities() {
		return this.cities;
	}

	public void setCities(Cities cities) {
		this.cities = cities;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_fk", nullable = false)
	public Countries getCountries() {
		return this.countries;
	}

	public void setCountries(Countries countries) {
		this.countries = countries;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner", nullable = false)
	public ServiceProviders getServiceProviders() {
		return this.serviceProviders;
	}

	public void setServiceProviders(ServiceProviders serviceProviders) {
		this.serviceProviders = serviceProviders;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "adress", nullable = false, length = 65535)
	public String getAdress() {
		return this.adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

	@Column(name = "email", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false, length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "zip", nullable = false, length = 10)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "street", nullable = false, length = 65535)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "longitude", nullable = false, precision = 22, scale = 0)
	public double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude", nullable = false, precision = 22, scale = 0)
	public double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_at", nullable = false, length = 10)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
