package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "categories", catalog = "bookall")
public class Categories implements java.io.Serializable {

	private Long id;
	private String name;
	private BusinessCategories businessCategories;

	public Categories() {
	}

	public Categories(String name) {
		this.name = name;
	}

	public Categories(String name, BusinessCategories businessCategories) {
		this.name = name;
		this.businessCategories = businessCategories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "categories")
	public BusinessCategories getBusinessCategories() {
		return this.businessCategories;
	}

	public void setBusinessCategories(BusinessCategories businessCategories) {
		this.businessCategories = businessCategories;
	}

}
