package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CorrespendenceUseridPushid generated by hbm2java
 */
@Entity
@Table(name = "correspendence_userid_pushid", catalog = "bookall")
public class CorrespendenceUseridPushid implements java.io.Serializable {

	private Long id;
	private Users users;
	private long pushId;

	public CorrespendenceUseridPushid() {
	}

	public CorrespendenceUseridPushid(Users users, long pushId) {
		this.users = users;
		this.pushId = pushId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_fk", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "pushId", nullable = false)
	public long getPushId() {
		return this.pushId;
	}

	public void setPushId(long pushId) {
		this.pushId = pushId;
	}

}
