package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CorrespendenceServicesProviderId generated by hbm2java
 */
@Embeddable
public class CorrespendenceServicesProviderId implements java.io.Serializable {

	private long providerFk;
	private long serviceFk;

	public CorrespendenceServicesProviderId() {
	}

	public CorrespendenceServicesProviderId(long providerFk, long serviceFk) {
		this.providerFk = providerFk;
		this.serviceFk = serviceFk;
	}

	@Column(name = "provider_fk", nullable = false)
	public long getProviderFk() {
		return this.providerFk;
	}

	public void setProviderFk(long providerFk) {
		this.providerFk = providerFk;
	}

	@Column(name = "service_fk", nullable = false)
	public long getServiceFk() {
		return this.serviceFk;
	}

	public void setServiceFk(long serviceFk) {
		this.serviceFk = serviceFk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CorrespendenceServicesProviderId))
			return false;
		CorrespendenceServicesProviderId castOther = (CorrespendenceServicesProviderId) other;

		return (this.getProviderFk() == castOther.getProviderFk()) && (this.getServiceFk() == castOther.getServiceFk());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getProviderFk();
		result = 37 * result + (int) this.getServiceFk();
		return result;
	}

}
