package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name = "countries", catalog = "bookall")
public class Countries implements java.io.Serializable {

	private Long id;
	private String name;
	private Set<Businesses> businesseses = new HashSet<Businesses>(0);

	public Countries() {
	}

	public Countries(String name) {
		this.name = name;
	}

	public Countries(String name, Set<Businesses> businesseses) {
		this.name = name;
		this.businesseses = businesseses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countries")
	public Set<Businesses> getBusinesseses() {
		return this.businesseses;
	}

	public void setBusinesseses(Set<Businesses> businesseses) {
		this.businesseses = businesseses;
	}

}
