package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Currencies generated by hbm2java
 */
@Entity
@Table(name = "currencies", catalog = "bookall")
public class Currencies implements java.io.Serializable {

	private Long id;
	private int code;
	private Set<Services> serviceses = new HashSet<Services>(0);

	public Currencies() {
	}

	public Currencies(int code) {
		this.code = code;
	}

	public Currencies(int code, Set<Services> serviceses) {
		this.code = code;
		this.serviceses = serviceses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false)
	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "currencies")
	public Set<Services> getServiceses() {
		return this.serviceses;
	}

	public void setServiceses(Set<Services> serviceses) {
		this.serviceses = serviceses;
	}

}
