package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DaySettings generated by hbm2java
 */
@Entity
@Table(name = "day_settings", catalog = "bookall")
public class DaySettings implements java.io.Serializable {

	private Long id;
	private String dayName;
	private Date startTime;
	private Date endTime;
	private Date breakStart;
	private Date breakEnd;
	private Set<WorkingPlans> workingPlanses = new HashSet<WorkingPlans>(0);

	public DaySettings() {
	}

	public DaySettings(String dayName, Date startTime, Date endTime, Date breakStart, Date breakEnd) {
		this.dayName = dayName;
		this.startTime = startTime;
		this.endTime = endTime;
		this.breakStart = breakStart;
		this.breakEnd = breakEnd;
	}

	public DaySettings(String dayName, Date startTime, Date endTime, Date breakStart, Date breakEnd,
			Set<WorkingPlans> workingPlanses) {
		this.dayName = dayName;
		this.startTime = startTime;
		this.endTime = endTime;
		this.breakStart = breakStart;
		this.breakEnd = breakEnd;
		this.workingPlanses = workingPlanses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "day_name", nullable = false, length = 10)
	public String getDayName() {
		return this.dayName;
	}

	public void setDayName(String dayName) {
		this.dayName = dayName;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "start_time", nullable = false, length = 8)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "end_time", nullable = false, length = 8)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "break_start", nullable = false, length = 8)
	public Date getBreakStart() {
		return this.breakStart;
	}

	public void setBreakStart(Date breakStart) {
		this.breakStart = breakStart;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "break_end", nullable = false, length = 8)
	public Date getBreakEnd() {
		return this.breakEnd;
	}

	public void setBreakEnd(Date breakEnd) {
		this.breakEnd = breakEnd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "daySettings")
	public Set<WorkingPlans> getWorkingPlanses() {
		return this.workingPlanses;
	}

	public void setWorkingPlanses(Set<WorkingPlans> workingPlanses) {
		this.workingPlanses = workingPlanses;
	}

}
