package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Favorites generated by hbm2java
 */
@Entity
@Table(name = "favorites", catalog = "bookall")
public class Favorites implements java.io.Serializable {

	private FavoritesId id;
	private Clients clients;
	private ServiceProviders serviceProviders;

	public Favorites() {
	}

	public Favorites(FavoritesId id, Clients clients, ServiceProviders serviceProviders) {
		this.id = id;
		this.clients = clients;
		this.serviceProviders = serviceProviders;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "description", column = @Column(name = "description", nullable = false, length = 65535)),
			@AttributeOverride(name = "clientId", column = @Column(name = "client_id", nullable = false)),
			@AttributeOverride(name = "serviceProviderId", column = @Column(name = "service_provider_id", nullable = false)),
			@AttributeOverride(name = "createdAt", column = @Column(name = "created_at", nullable = false, length = 10)),
			@AttributeOverride(name = "updatedAt", column = @Column(name = "updated_at", nullable = false, length = 10)) })
	public FavoritesId getId() {
		return this.id;
	}

	public void setId(FavoritesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "client_id", nullable = false, insertable = false, updatable = false)
	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service_provider_id", nullable = false, insertable = false, updatable = false)
	public ServiceProviders getServiceProviders() {
		return this.serviceProviders;
	}

	public void setServiceProviders(ServiceProviders serviceProviders) {
		this.serviceProviders = serviceProviders;
	}

}
