package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FavoritesId generated by hbm2java
 */
@Embeddable
public class FavoritesId implements java.io.Serializable {

	private long id;
	private String description;
	private long clientId;
	private long serviceProviderId;
	private Date createdAt;
	private Date updatedAt;

	public FavoritesId() {
	}

	public FavoritesId(long id, String description, long clientId, long serviceProviderId, Date createdAt,
			Date updatedAt) {
		this.id = id;
		this.description = description;
		this.clientId = clientId;
		this.serviceProviderId = serviceProviderId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Column(name = "id", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "client_id", nullable = false)
	public long getClientId() {
		return this.clientId;
	}

	public void setClientId(long clientId) {
		this.clientId = clientId;
	}

	@Column(name = "service_provider_id", nullable = false)
	public long getServiceProviderId() {
		return this.serviceProviderId;
	}

	public void setServiceProviderId(long serviceProviderId) {
		this.serviceProviderId = serviceProviderId;
	}

	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "updated_at", nullable = false, length = 10)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoritesId))
			return false;
		FavoritesId castOther = (FavoritesId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& (this.getClientId() == castOther.getClientId())
				&& (this.getServiceProviderId() == castOther.getServiceProviderId())
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this.getCreatedAt().equals(castOther.getCreatedAt())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (int) this.getClientId();
		result = 37 * result + (int) this.getServiceProviderId();
		result = 37 * result + (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		return result;
	}

}
