package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NotificationTypes generated by hbm2java
 */
@Entity
@Table(name = "notification_types", catalog = "bookall")
public class NotificationTypes implements java.io.Serializable {

	private long typeId;
	private NotificationMessages notificationMessages;
	private Set<Notifications> notificationses = new HashSet<Notifications>(0);

	public NotificationTypes() {
	}

	public NotificationTypes(long typeId, NotificationMessages notificationMessages) {
		this.typeId = typeId;
		this.notificationMessages = notificationMessages;
	}

	public NotificationTypes(long typeId, NotificationMessages notificationMessages,
			Set<Notifications> notificationses) {
		this.typeId = typeId;
		this.notificationMessages = notificationMessages;
		this.notificationses = notificationses;
	}

	@Id

	@Column(name = "type_id", unique = true, nullable = false)
	public long getTypeId() {
		return this.typeId;
	}

	public void setTypeId(long typeId) {
		this.typeId = typeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "notification_message_fk", nullable = false)
	public NotificationMessages getNotificationMessages() {
		return this.notificationMessages;
	}

	public void setNotificationMessages(NotificationMessages notificationMessages) {
		this.notificationMessages = notificationMessages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notificationTypes")
	public Set<Notifications> getNotificationses() {
		return this.notificationses;
	}

	public void setNotificationses(Set<Notifications> notificationses) {
		this.notificationses = notificationses;
	}

}
