package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NotificationMessages generated by hbm2java
 */
@Entity
@Table(name = "notification_messages", catalog = "bookall")
public class NotificationMessages implements java.io.Serializable {

	private Long id;
	private String message;
	private Set<NotificationTypes> notificationTypeses = new HashSet<NotificationTypes>(0);

	public NotificationMessages() {
	}

	public NotificationMessages(String message) {
		this.message = message;
	}

	public NotificationMessages(String message, Set<NotificationTypes> notificationTypeses) {
		this.message = message;
		this.notificationTypeses = notificationTypeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "message", nullable = false, length = 50)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notificationMessages")
	public Set<NotificationTypes> getNotificationTypeses() {
		return this.notificationTypeses;
	}

	public void setNotificationTypeses(Set<NotificationTypes> notificationTypeses) {
		this.notificationTypeses = notificationTypeses;
	}

}
