package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payements generated by hbm2java
 */
@Entity
@Table(name = "payements", catalog = "bookall")
public class Payements implements java.io.Serializable {

	private Long id;
	private Clients clients;
	private PayementTypes payementTypes;
	private Date createdAt;
	private Date updatedAt;
	private Set<Receipts> receiptses = new HashSet<Receipts>(0);

	public Payements() {
	}

	public Payements(Clients clients, PayementTypes payementTypes, Date createdAt, Date updatedAt) {
		this.clients = clients;
		this.payementTypes = payementTypes;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Payements(Clients clients, PayementTypes payementTypes, Date createdAt, Date updatedAt,
			Set<Receipts> receiptses) {
		this.clients = clients;
		this.payementTypes = payementTypes;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.receiptses = receiptses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "client_fk", nullable = false)
	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payement_type_fk", nullable = false)
	public PayementTypes getPayementTypes() {
		return this.payementTypes;
	}

	public void setPayementTypes(PayementTypes payementTypes) {
		this.payementTypes = payementTypes;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_at", nullable = false, length = 10)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "payements")
	public Set<Receipts> getReceiptses() {
		return this.receiptses;
	}

	public void setReceiptses(Set<Receipts> receiptses) {
		this.receiptses = receiptses;
	}

}
