package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PayementTypes generated by hbm2java
 */
@Entity
@Table(name = "payement_types", catalog = "bookall")
public class PayementTypes implements java.io.Serializable {

	private long typeId;
	private Types types;
	private Set<Payements> payementses = new HashSet<Payements>(0);

	public PayementTypes() {
	}

	public PayementTypes(Types types) {
		this.types = types;
	}

	public PayementTypes(Types types, Set<Payements> payementses) {
		this.types = types;
		this.payementses = payementses;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "types"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "type_id", unique = true, nullable = false)
	public long getTypeId() {
		return this.typeId;
	}

	public void setTypeId(long typeId) {
		this.typeId = typeId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Types getTypes() {
		return this.types;
	}

	public void setTypes(Types types) {
		this.types = types;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "payementTypes")
	public Set<Payements> getPayementses() {
		return this.payementses;
	}

	public void setPayementses(Set<Payements> payementses) {
		this.payementses = payementses;
	}

}
