package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reviews generated by hbm2java
 */
@Entity
@Table(name = "reviews", catalog = "bookall")
public class Reviews implements java.io.Serializable {

	private Long id;
	private Clients clients;
	private ReviewResponses reviewResponses;
	private ServiceProviders serviceProviders;
	private int rating;
	private boolean isAnswered;
	private Date answeredAt;

	public Reviews() {
	}

	public Reviews(Clients clients, ReviewResponses reviewResponses, ServiceProviders serviceProviders, int rating,
			boolean isAnswered, Date answeredAt) {
		this.clients = clients;
		this.reviewResponses = reviewResponses;
		this.serviceProviders = serviceProviders;
		this.rating = rating;
		this.isAnswered = isAnswered;
		this.answeredAt = answeredAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "client_fk", nullable = false)
	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "review_response_fk", nullable = false)
	public ReviewResponses getReviewResponses() {
		return this.reviewResponses;
	}

	public void setReviewResponses(ReviewResponses reviewResponses) {
		this.reviewResponses = reviewResponses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service_provider_fk", nullable = false)
	public ServiceProviders getServiceProviders() {
		return this.serviceProviders;
	}

	public void setServiceProviders(ServiceProviders serviceProviders) {
		this.serviceProviders = serviceProviders;
	}

	@Column(name = "rating", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Column(name = "is_answered", nullable = false)
	public boolean isIsAnswered() {
		return this.isAnswered;
	}

	public void setIsAnswered(boolean isAnswered) {
		this.isAnswered = isAnswered;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "answered_at", nullable = false, length = 10)
	public Date getAnsweredAt() {
		return this.answeredAt;
	}

	public void setAnsweredAt(Date answeredAt) {
		this.answeredAt = answeredAt;
	}

}
