package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ServiceproviderSettings generated by hbm2java
 */
@Entity
@Table(name = "serviceprovider_settings", catalog = "bookall")
public class ServiceproviderSettings implements java.io.Serializable {

	private Long settingId;
	private Settings settings;
	private WorkingPlans workingPlans;

	public ServiceproviderSettings() {
	}

	public ServiceproviderSettings(Settings settings, WorkingPlans workingPlans) {
		this.settings = settings;
		this.workingPlans = workingPlans;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "settings"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "setting_id", unique = true, nullable = false)
	public Long getSettingId() {
		return this.settingId;
	}

	public void setSettingId(Long settingId) {
		this.settingId = settingId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Settings getSettings() {
		return this.settings;
	}

	public void setSettings(Settings settings) {
		this.settings = settings;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "working_plan_fk", nullable = false)
	public WorkingPlans getWorkingPlans() {
		return this.workingPlans;
	}

	public void setWorkingPlans(WorkingPlans workingPlans) {
		this.workingPlans = workingPlans;
	}

}
