package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ServiceCategories generated by hbm2java
 */
@Entity
@Table(name = "service_categories", catalog = "bookall")
public class ServiceCategories implements java.io.Serializable {

	private long categoryId;
	private Set<Services> serviceses = new HashSet<Services>(0);

	public ServiceCategories() {
	}

	public ServiceCategories(long categoryId) {
		this.categoryId = categoryId;
	}

	public ServiceCategories(long categoryId, Set<Services> serviceses) {
		this.categoryId = categoryId;
		this.serviceses = serviceses;
	}

	@Id

	@Column(name = "category_id", unique = true, nullable = false)
	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceCategories")
	public Set<Services> getServiceses() {
		return this.serviceses;
	}

	public void setServiceses(Set<Services> serviceses) {
		this.serviceses = serviceses;
	}

}
