package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Unavailabilities generated by hbm2java
 */
@Entity
@Table(name = "unavailabilities", catalog = "bookall")
public class Unavailabilities implements java.io.Serializable {

	private Long id;
	private WorkingPlans workingPlans;
	private float start;
	private float end;
	private int duration;

	public Unavailabilities() {
	}

	public Unavailabilities(WorkingPlans workingPlans, float start, float end, int duration) {
		this.workingPlans = workingPlans;
		this.start = start;
		this.end = end;
		this.duration = duration;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "working_plan_fk", nullable = false)
	public WorkingPlans getWorkingPlans() {
		return this.workingPlans;
	}

	public void setWorkingPlans(WorkingPlans workingPlans) {
		this.workingPlans = workingPlans;
	}

	@Column(name = "start", nullable = false, precision = 12, scale = 0)
	public float getStart() {
		return this.start;
	}

	public void setStart(float start) {
		this.start = start;
	}

	@Column(name = "end", nullable = false, precision = 12, scale = 0)
	public float getEnd() {
		return this.end;
	}

	public void setEnd(float end) {
		this.end = end;
	}

	@Column(name = "duration", nullable = false)
	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

}
