package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "bookall")
public class Users implements java.io.Serializable {

	private long id;
	private String username;
	private String firstname;
	private String lastname;
	private String email;
	private String phone;
	private Date createdAt;
	private Date updatedAt;
	private Set<CorrespendenceUseridPushid> correspendenceUseridPushids = new HashSet<CorrespendenceUseridPushid>(0);
	private Clients clients;
	private ServiceProviders serviceProviders;
	private Set<Roles> roleses = new HashSet<Roles>(0);

	public Users() {
	}

	public Users(long id, String username, String firstname, String lastname, String email, String phone,
			Date createdAt, Date updatedAt) {
		this.id = id;
		this.username = username;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.phone = phone;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Users(long id, String username, String firstname, String lastname, String email, String phone,
			Date createdAt, Date updatedAt, Set<CorrespendenceUseridPushid> correspendenceUseridPushids,
			Clients clients, ServiceProviders serviceProviders, Set<Roles> roleses) {
		this.id = id;
		this.username = username;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.phone = phone;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.correspendenceUseridPushids = correspendenceUseridPushids;
		this.clients = clients;
		this.serviceProviders = serviceProviders;
		this.roleses = roleses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 10)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "firstname", nullable = false, length = 20)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 20)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false, length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_at", nullable = false, length = 10)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<CorrespendenceUseridPushid> getCorrespendenceUseridPushids() {
		return this.correspendenceUseridPushids;
	}

	public void setCorrespendenceUseridPushids(Set<CorrespendenceUseridPushid> correspendenceUseridPushids) {
		this.correspendenceUseridPushids = correspendenceUseridPushids;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "users")
	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "users")
	public ServiceProviders getServiceProviders() {
		return this.serviceProviders;
	}

	public void setServiceProviders(ServiceProviders serviceProviders) {
		this.serviceProviders = serviceProviders;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "correspendence_user_roles", catalog = "bookall", joinColumns = {
			@JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "role_id", nullable = false, updatable = false) })
	public Set<Roles> getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set<Roles> roleses) {
		this.roleses = roleses;
	}

}
