package entities;
// Generated 24 mai 2020 05:58:50 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WorkingPlans generated by hbm2java
 */
@Entity
@Table(name = "working_plans", catalog = "bookall")
public class WorkingPlans implements java.io.Serializable {

	private Long id;
	private DaySettings daySettings;
	private Set<ServiceproviderSettings> serviceproviderSettingses = new HashSet<ServiceproviderSettings>(0);
	private Set<Unavailabilities> unavailabilitieses = new HashSet<Unavailabilities>(0);
	private Set<Availabilites> availabiliteses = new HashSet<Availabilites>(0);

	public WorkingPlans() {
	}

	public WorkingPlans(DaySettings daySettings) {
		this.daySettings = daySettings;
	}

	public WorkingPlans(DaySettings daySettings, Set<ServiceproviderSettings> serviceproviderSettingses,
			Set<Unavailabilities> unavailabilitieses, Set<Availabilites> availabiliteses) {
		this.daySettings = daySettings;
		this.serviceproviderSettingses = serviceproviderSettingses;
		this.unavailabilitieses = unavailabilitieses;
		this.availabiliteses = availabiliteses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "day_fk", nullable = false)
	public DaySettings getDaySettings() {
		return this.daySettings;
	}

	public void setDaySettings(DaySettings daySettings) {
		this.daySettings = daySettings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workingPlans")
	public Set<ServiceproviderSettings> getServiceproviderSettingses() {
		return this.serviceproviderSettingses;
	}

	public void setServiceproviderSettingses(Set<ServiceproviderSettings> serviceproviderSettingses) {
		this.serviceproviderSettingses = serviceproviderSettingses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workingPlans")
	public Set<Unavailabilities> getUnavailabilitieses() {
		return this.unavailabilitieses;
	}

	public void setUnavailabilitieses(Set<Unavailabilities> unavailabilitieses) {
		this.unavailabilitieses = unavailabilitieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workingPlans")
	public Set<Availabilites> getAvailabiliteses() {
		return this.availabiliteses;
	}

	public void setAvailabiliteses(Set<Availabilites> availabiliteses) {
		this.availabiliteses = availabiliteses;
	}

}
